version: "3.1"

services:
  postgres:
    image: postgres:10
    container_name: itss2_postgres
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - itss2:/var/lib/postgresql/data

volumes:
  itss2:
