export const ENV_KEY = {
  NODE_ENV: 'NODE_ENV',

  APP_NAME: 'APP_NAME',
  PORT: 'PORT',
  PREFIX: 'PREFIX',

  DATABASE_URL: 'DATABASE_URL',

  JWT_ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',

  AWS_S3_REGION: 'AWS_S3_REGION',
  AWS_S3_ACCESS_KEY_ID: 'AWS_S3_ACCESS_KEY_ID',
  AWS_S3_SECRET_ACCESS_KEY: 'AWS_S3_SECRET_ACCESS_KEY',
  AWS_S3_BUCKET_NAME: 'AWS_S3_BUCKET_NAME',
  AWS_S3_URL: 'AWS_S3_URL',
};
